
const names=[
    {
        id:1,
        name:"Pepper",
        email:"Pepper@p.com"
    },
    {
        id:2,
        name:"Missy",
        email:"Missy@m.com"
    },
    {
        id:3,
        name:"Snuggles",
        email:"Snuggles@s.com"
    },
    {
        id:4,
        name:"Simba",
        email:"Simba@s.com"
    },
    {
        id:5,
        name:"Princess",
        email:"Princess@p.com"
    },
    {
        id:6,
        name:"Socks",
        email:"Socks@s.com"
    },
    {
        id:7,
        name:"Whiskers",
        email:"Whiskers@w.com"
    },
    {
        id:8,
        name:"Trouble",
        email:"Trouble@t.com"
    },
    {
        id:9,
        name:"Spooky",
        email:"Spooky@s.com"
    },
    {
        id:10,
        name:"Zoe",
        email:"Zoe@z.com"
    },
    {
        id:11,
        name:"Spohie",
        email:"Sophie@s.com"
    },
    {
        id:12,
        name:"Scooter",
        email:"Scooter@s.com"
    },
    {
        id:13,
        name:"Olivia",
        email:"Olivia@o.com"
    },
    {
        id:14,
        name:"Willow",
        email:"Willow@w.com"
    },
    {
        id:15,
        name:"Salem",
        email:"Salem@s.com"
    },
    {
        id:16,
        name:"Rocky",
        email:"Rocky@r.com"
    },
    {
        id:17,
        name:"Fluufy",
        email:"Fluffy@f.com"
    },
    {
        id:18,
        name:"Balley",
        email:"Balley@b.com"
    },
    {
        id:19,
        name:"Loki",
        email:"Loki@r.com"
    },
    {
        id:20,
        name:"Coco",
        email:" Coco@c.com"
    },
    {
        id:21,
        name:"Sassy",
        email:"Sassy@s.com"
    },
    {
        id:22,
        name:"Jack",
        email:"Jack@j.com"
    },
    {
        id:23,
        name:"Snowball",
        email:"Snowball@s.com"
    },
    {
        id:24,
        name:"Shadow",
        email:"Shadow@s.com"
    },
    {
        id:25,
        name:"Pumkin",
        email:"Pumkin@p.com"
    },
    {
        id:26,
        name:"Daisy",
        email:"Daisy@d.com"
    },
    {
        id:27,
        name:"Midnight",
        email:"Midnight@m.com"
    },
    {
        id:28,
        name:"Cookie",
        email:"Cookie@c.com"
    },
    {
        id:29,
        name:"Abby",
        email:"Abby@a.com"
    },
    {
        id:30,
        name:"Bandit",
        email:"Bandit@b.com"
    }
    
]
export default names